language: java
jdk:
   - oraclejdk9
addons:
   sonarcloud:
      organization: "begriffi18-github"
      token:
         secure: 6e95e4a9d9439141d78d2f2aaa870364ba0f773e
script:
   mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
